---
- name: update apt
  apt: update_cache=yes


- name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest

- name: Set up nginx
  template:
      src: "templates/nginconf.j2"
      dest: "/etc/nginx/sites-enabled/{{ http_conf }}"

- name: Remove a file, if present
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: nginx restart
