---
- name: update apt
  apt: update_cache=yes
 
- name: install apache
  apt: name=apache2 state=latest

- name: portconfig 8080
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
  notify: restart apache

- name: Set up Apache virtualhost
  template:
      src: templates/apache.conf.j2
      dest: /etc/apache2/sites-available/{{ http_conf }}

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: restart apache

